#! /usr/bin/env bash

# Source utility scripts and vars
. /etc/blockets/blockets.env

# Optional source term colors var
. /etc/blockets/colors.env

# Set the ME var which is used project wide
export ME=example

# Project specific vars and scripts
. ${ENV}/${ME}.env

# Loop through the args which reperesent scripts
# in the tasks/${ME}/ dir

for task in "$@"
do
	if [[ -e ${TASKS}/${ME}/${task}.sh ]]
	then
		echo "${TASKS}/${ME}/${task}.sh"
		${TASKS}/${ME}/${task}.sh
	else
		echo "[ERROR] Not found: ${TASKS}/${ME}/${task}.sh"
		exit 1
	fi
done
